name: excel_community
description: A community-maintained fork of the excel library for reading, creating, editing and updating excel sheets. Supports XLSX format with client and server-side compatibility, including chart support.
version: 1.0.3
homepage: https://github.com/decksplayer/excel_community
repository: https://github.com/decksplayer/excel_community
issue_tracker: https://github.com/decksplayer/excel_community/issues
topics:
  - excel
  - office
  - storage
  - sheets
  - spreadsheet

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  web: ^1.1.1
  archive: ">=4.0.9 <=5.0.0"
  xml: ^6.6.1
  collection: ^1.19.1
  equatable: ^2.0.8

dev_dependencies:
  test: ^1.30.0
  lints: ^6.1.0

